### ISSUE TITLE
Setup Nuxt Content site with Docs

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/financial-freedom#65]
# ToDo
- [ ] Configure domain financialfreedom.app
- [ ] Have automated builds with CloudFlare
- [x] Ensure a spot is available for the landing page
- [x] Ensure the docs are loading
