### ISSUE TITLE
Local Development: Get new version of Spin configured

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/financial-freedom#68]
### ToDo

- [x] Update local files
- [ ] Update documentation

### Compatibility check
- [ ] Ensure this works on macOS
- [ ] Ensure it works on Windows
- [ ] Ensure it works on Ubuntu 22.04

### Other possible changes
- [ ] Fix permission issue (https://github.com/serversideup/docker-php/issues/179)
