### ISSUE TITLE
Expand Email Sign Up Section

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/financial-freedom#95]
![Image](https://github.com/serversideup/financial-freedom/assets/3174134/09bcd69f-4022-4695-8eb4-ca469c52cac2)

### 🎨 Figma File
https://www.figma.com/file/JIJGYut8HuSyYourCsgy1J/Financial-Freedom-Designs?type=design&node-id=8723-151413&mode=design&t=NwJlir5j6u2sBbgW-11

## Todo

- [x] Add our profile images
- [x] Link to our social profiles
- [x] Ensure this displays on mobile well

### Add to other projects
- [x] Docker PHP
- [x] Spin
